name: "Shanggyx's blog"
description: "上官云霄的个人博客"

avatar: https://shanggyx.github.io/images/avatar.png
favicon: https://shanggyx.github.io/images/favicon.ico

navigation:
  - name: 首页
    url: /
  - name: 关于
    url: /about
  - name: 分类
    url: /tags

paginate: 8

excerpt_separator: <!-- more -->

footer-links:
  zhihu: 
  email: LRiyuan007919@163.com
  facebook:
  github: Shanggyx
  rss: # just type anything here for a working RSS icon
  twitter: 
  youtube:

footer-text: Copyright (c) 2024 Shanggyx

url: https://shanggyx.github.io

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
markdown: kramdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

codeblock:
  highlight_theme: night eighties		# 高亮代码块的主题风格，有五种选择，请看下面表格
  copy_button:		
    enable: true				# 是否使用复制按钮
    show_result: true				# 实现复制结果，一般是`复制成功`
    style:

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

